Bump Dasharo Coreboot / hotp-verification; fix nitropad-nxx ec-powerdown
linuxboot/heads pull request #1561
Opened 2023-12-22 14:35 UTC by daringer

This is the upstream relevant part of Nitrokey's [next release](https://github.com/Nitrokey/heads/tree/nitropad-release-v2.4) for the Nitropads, it consists of three parts:

1) update Dasharo Coreboot to the most recent version (1.7.2)
  * all previous coreboot patches are now upstreamed and removed
  * added a minimal-change patch to switch available S-states based on model during compile-time
  * fixes: https://github.com/Nitrokey/heads/issues/29 (suspend compatibility improved, see below)
  * fixes: https://github.com/Nitrokey/heads/issues/25 (see tests below)
  * fixes: https://github.com/Nitrokey/heads/issues/32 (part of the dasharo coreboot bump)
  
2) fix watchdog-based powerdown for `nitropad-nxx` 
* fixes: https://github.com/Nitrokey/heads/issues/24

3) updates `hotp-verification` to obey Nitrokey 3's extended security model
  * older `hotp-verification` versions + NK3 v1.6 will not allow overwriting the HOTP secret, workaround: delete it manually using `nitropy`
  * using this `hotp-verification` version the HOTP secret is first removed before setting it again during HOTP regeneration
  * this change is fully backwards compatible with any previously working tokens
  
### Test Results

First round of tests was done for `t430-hotp-max`, `nitropad-nv41`, `nitropad-ns50`:
* QubesOS / ubuntu regular boot + installation
* splash screen visible
* flashing using the build-time-provided `.zip`
* suspend ns50 (S0ix) -> QubesOS (not ok/expected), Ubuntu (ok)
* suspend nv41 (S3) -> QubesOS (ok), Ubuntu (ok)
* igfx availability (nv41/ns50) inside Ubuntu (ok)
* igfx availability (nv41/ns50) inside QubesOS (4.1.2) still `llvm-pipe`, works with QubesOS 4.2
* branding and vendor reconfiguration works as expected (`site-local`)
* Nitrokey 3 HOTP with firmware <v1.6 & >=v1.6

We plan for another round of testing early in January, once these tests confirm the listed ones - I'll change the PR to be ready-for-review.

2023-12-23 21:24 UTC, tlaurion commented
@JonathonHall-Purism time to test hotp for regression and approve?

2023-12-29 21:05 UTC, tlaurion commented
Tested without regression
- Untested_w530-hotp-maximized (new main machine)

2023-12-29 21:07 UTC, tlaurion requested changes

2023-12-29 21:07 UTC, tlaurion commented on config/coreboot-nitropad-ns50.config
> +CONFIG_SMMSTORE=y
@daringer Will you remove those?

2023-12-29 21:07 UTC, tlaurion commented on config/coreboot-nitropad-nv41.config
> +CONFIG_SMMSTORE=y
@daringer Will you remove those?

2023-12-29 21:07 UTC, tlaurion commented on modules/hotp-verification
> +hotp-verification_version := 70c04f51387eee8f777e943ba83b6405764a3cd2
No regression observed on Nitrokey Pro storage 2 used for HOTP and factory reset.

2024-01-02 11:15 UTC, daringer commented
At this point we cannot get rid of the `SMMSTORE` - Dasharo introduces reading from it [here](https://github.com/Dasharo/coreboot/blob/novacustom_nv4x_adl_v1.7.2/src/vendorcode/dasharo/options.c#L20):  This means that currently any Dasharo build is implicitly depending on `SMMSTORE` (even if it's not explicitly set in the configs, it will be pulled in via EDK2). Removing this might be possible, but is quite a bigger changeset which we would have to introduce and I cannot oversee currently if this would introduce regressions of some kind.

2024-01-02 18:08 UTC, daringer commented
We also did another full test iteration today, fully confirmed what is written in "Test Results" in the initial post

2024-01-03 19:19 UTC, JonathonHall-Purism approved these changes
Tested Librem 14 + Librem Key, looks good to me.  Thanks @daringer

2024-01-03 20:49 UTC, tlaurion approved these changes

2024-01-03 20:49 UTC, merged